### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by bfack95** [karthikpanicker/automatictactoe#5]
https://automatictactoe.com/apps/etsy/ leads to a 404 error. Also, etsy orders no longer being pulled into trello. Looks like there was an update that broke the automation.

**Comment by karthikpanicker** [comment]
@bfack95 The esty account that had this app registered got suspended. I have recovered it from suspension, but looks like I need to recreate the app. Will try to sort this out in a days time.

**Comment by bfack95** [comment]
Thank you! This automation is literally the cornerstone of the project management for my business. Your work is very much appreciated!

**Comment by karthikpanicker** [comment]
@bfack95 This should be fixed now. They have reinstated the app. Please let me know if you face any other issues.

**Comment by bfack95** [comment]
Thank you so much! very much appreciated!!!
